server:
  tomcat:
    uri-encoding: UTF-8

spring:
  sleuth:
    reactor:
      instrumentation-type: decorate_on_each
    baggage:
      remote-fields:
        - user_info
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-bean-definition-overriding: true
    banner-mode: log
  cloud:
    sentinel:
      eager: true
    # 开启断路器功能，默认开启
    circuitbreaker:
      sentinel:
        enabled: true
    circuit:
      breaker:
        enabled: true
    loadbalancer:
      # 使用nacos作为负载均衡的实例选择策略
      nacos:
        enabled: true
      retry:
        enabled: true
        # 对当前实例重试的次数，默认值: 0
        max-retries-on-same-service-instance: 0
        # 切换实例进行重试的次数，默认值: 1
        max-retries-on-next-service-instance: 2
        # 对所有的操作请求都进行重试，默认false，默认只对GET请求进行重试
        retry-on-all-operations: false
#feign配置
feign:
  okhttp:
    enabled: true
  # 开启sentinel feign断路器
  sentinel:
    enabled: true
  circuitbreaker:
    enabled: false
  httpclient:
    enabled: false
  client:
    config:
      default:
        #feign客户端建立连接超时时间
        connect-timeout: 3000
        #feign客户端建立连接后读取资源超时时间
        read-timeout: 5000

logging:
  file:
    path: ${LOGGING_PATH:logs}

icloud:
  jwt:
    secret: '9MvU1S1!8*PXlg*Z81jaec*$ha0wTIKa3asdyPC*RxMILrx69iPZh#s^fU&1d89d'
    expired: 72h
  swagger:
    enabled: true
#knife4j配置
knife4j:
  #启用
  enable: true
  #基础认证
  basic:
    enable: true
    username: admin
    password: admin

