spring:
  application:
    name: gateway
  profiles:
    include: launch
  cloud:
    gateway:
      httpclient:
        connect-timeout: 3000
        response-timeout: 30s
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

server:
  port: 18100

icloud:
  swagger:
    document:
      resources:
        - name: 账号模块
          url: user
        - name: 认证模块
          url: auth

logging:
  level:
    # 开启网关路由调试日志
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
